=== COMP4711TAK/Lab7/data/schedule.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
Course schedule data for British Columbia Institute of Technology
-->

<!-- Schedule constraints -->
<!ELEMENT schedule (year, semester, set, program, days, periods, courses)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT semester (#PCDATA)>
<!ELEMENT set (#PCDATA)>
<!ELEMENT program (#PCDATA)>

<!-- Days constraints -->
<!ELEMENT days (day+)>
<!ELEMENT day (day_of_the_week, booking+)>
<!ELEMENT day_of_the_week (#PCDATA)>

<!-- Periods constraints -->
<!ELEMENT periods (timeslot+)>
<!ELEMENT timeslot (booking+)>
<!ATTLIST timeslot startTime (8:30|9:30|10:30|11:30|12:30|1:30|2:30|3:30|4:30) #REQUIRED>

<!-- Courses constraints -->
<!ELEMENT courses (course+)>
<!ELEMENT course (id, title, instructor, booking+)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT instructor (first_name, last_name)>
<!ELEMENT first_name (#PCDATA)>
<!ELEMENT last_name (#PCDATA)>

<!-- Booking constraints -->
<!ELEMENT booking (room, instructor?)>
<!ELEMENT room (building, number)>
<!ELEMENT building (#PCDATA)>
<!ELEMENT number (#PCDATA)>
<!ATTLIST booking
		  type (lecture|lab) #REQUIRED
          course (BLAW3600|COMP4735|COMP4977|COMP4560|COMP4711|COMP4976) #IMPLIED
          day (Monday|Tuesday|Wednesday|Thursday|Friday) #IMPLIED
          time (8:30|9:30|10:30|11:30|12:30|1:30|2:30|3:30|4:30) #IMPLIED
	      >

=== COMP4711TAK/Lab7/data/schedule.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE schedule SYSTEM 'schedule.dtd'>
<!--
All of the courses in each day for British Columbia Institute of Technology
-->
<schedule>
    <year>2016</year>
    <semester>Fall</semester>
    <set>4S</set>
    <program>CST</program>
    <days>
        <day>
            <day_of_the_week>Monday</day_of_the_week>
            <booking time="9:30" course="BLAW3600" type="lecture">
                <room>
                    <building>SW3</building>
                    <number>4785</number>
                </room>
                <instructor>
                    <first_name>Catherine</first_name>
                    <last_name>Ryan</last_name>
                </instructor>
            </booking>
            <booking time="10:30" course="COMP4735" type="lecture">
                <room>
                    <building>SW1</building>
                    <number>1205</number>
                </room>
                <instructor>
                    <first_name>Mirela</first_name>
                    <last_name>Gutica</last_name>
                </instructor>
            </booking>
            <booking time="12:30" course="COMP4735" type="lab">
                <room>
                    <building>SE12</building>
                    <number>320</number>
                </room>
                <instructor>
                    <first_name>Mirela</first_name>
                    <last_name>Gutica</last_name>
                </instructor>
            </booking>
        </day>
    </days>
    <periods>
        <timeslot startTime="11:30">
            <booking day="Monday" course="COMP4735" type="lecture">
                <room>
                    <building>SW1</building>
                    <number>1205</number>
                </room>
                <instructor>
                    <first_name>Mirela</first_name>
                    <last_name>Gutica</last_name>
                </instructor>
            </booking>
            <booking day="Tuesday" course="COMP4560" type="lecture">
                <room>
                    <building>SW5</building>
                    <number>1850</number>
                </room>
                <instructor>
                    <first_name>Brenda</first_name>
                    <last_name>Fine</last_name>
                </instructor>
            </booking>
            <booking day="Thursday" course="COMP4735" type="lecture">
                <room>
                    <building>SW3</building>
                    <number>1710</number>
                </room>
                <instructor>
                    <first_name>Mirela</first_name>
                    <last_name>Gutica</last_name>
                </instructor>
            </booking>
        </timeslot>
    </periods>
    <courses>
        <course>
            <id>COMP4560</id>
            <title>Computer Graphics for CST</title>
            <instructor>
                <first_name>Brenda</first_name>
                <last_name>Fine</last_name>
            </instructor>
            <booking time="11:30" day="Tuesday" type="lecture">
                <room>
                    <building>SW5</building>
                    <number>1850</number>
                </room>
            </booking>
            <booking time="3:30" day="Tuesday" type="lab">
                <room>
                    <building>SE12</building>
                    <number>322</number>
                </room>
            </booking>
            <booking time="12:30" day="Friday" type="lecture">
                <room>
                    <building>SW3</building>
                    <number>308</number>
                </room>
            </booking>
        </course>
    </courses>
</schedule>
